name: Create release when tag is pushed

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build and test
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    - name: "✏️ Generate release changelog"
      uses: heinrichreimer/github-changelog-generator-action@v2.3

    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "build/libs/protech-doctolib-0.0.1-SNAPSHOT-javadoc.jar,build/libs/protech-doctolib-0.0.1-SNAPSHOT-sources.jar"

